In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
 df = pd.read_csv("/content/drive/MyDrive/complete_dataset.csv")

In [ ]:
df.head()

modelMag_u  modelMag_g  modelMag_r  modelMag_i  modelMag_z  fiberMag_u  \
0    0.001875    0.024946    1.073536    0.098735    0.124608   -0.001200   
1    0.037172    0.041055    0.404224    0.015898    0.010719    0.020721   
2    0.071321    0.051603    0.823187    0.026963    0.017246    0.046143   
3   -0.049880   -0.056115   -1.855847   -0.119150   -0.120956   -0.036716   
4    0.046443    0.031985    0.332529    0.010698    0.002047    0.033888   

   fiberMag_g  fiberMag_r  fiberMag_i  fiberMag_z  ...      mmug      mmgr  \
0    0.017518    0.995311    0.096295    0.115285  ...  0.013955  0.059661   
1    0.032666    0.338425    0.007471   -0.000585  ...  0.040710  0.054073   
2    0.047539    0.955438    0.029321    0.018973  ...  0.063974  0.078169   
3   -0.049527   -2.039592   -0.131198   -0.132498  ... -0.055161 -0.116107   
4    0.039251    0.667807    0.028947    0.018181  ...  0.040817  0.042697   

       mmri      mmiz      mfug      mfgr      mfri      mfiz    z_phot  label  
0  0.169960  0.136614  0.008492  0.043766  0.162180  0.122070  1.802092      1  
1  0.042859  0.016281  0.027783  0.041560  0.030038  0.003973  2.003878      1  
2  0.081904  0.027041  0.048753  0.072699  0.092979  0.027863  2.069658      1  
3 -0.242623 -0.146867 -0.044881 -0.103298 -0.266642 -0.152137  1.228064      1  
4  0.032893  0.007796  0.038062  0.056830  0.073386  0.027191  3.268066      1  

[5 rows x 28 columns]

In [ ]:
features = list(df.columns)
features.pop(-1)

features

['modelMag_u',
 'modelMag_g',
 'modelMag_r',
 'modelMag_i',
 'modelMag_z',
 'fiberMag_u',
 'fiberMag_g',
 'fiberMag_r',
 'fiberMag_i',
 'fiberMag_z',
 'petroR50_r',
 'petroR90_r',
 'petroR50_z',
 'petroR90_z',
 'r',
 'i',
 'z',
 'zerr',
 'mmug',
 'mmgr',
 'mmri',
 'mmiz',
 'mfug',
 'mfgr',
 'mfri',
 'mfiz',
 'z_phot']

In [ ]:
len(features)

27

In [ ]:
x = df[features]
y = df['label']

In [ ]:
label_encoded = y[:, np.newaxis]
label_encoded

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  """Entry point for launching an IPython kernel.


array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
one_hot_encoder = OneHotEncoder(sparse=False)
one_hot_encoded = one_hot_encoder.fit_transform(label_encoded)
y = one_hot_encoded
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.1, random_state=42)
train_x, val_x, train_y, val_y = train_test_split(train_x, train_y, test_size=0.1, random_state=42)

print(len(train_x), len(val_x),len(test_x))

41823 4647 5164


In [ ]:
train_x

modelMag_u  modelMag_g  modelMag_r  modelMag_i  modelMag_z  fiberMag_u  \
37223    0.080547    0.065414    1.286601    0.060848    0.046780    0.060153   
43793   -0.072319   -0.062589   -1.748169   -0.102296   -0.094765   -0.019046   
48047    0.002246    0.005641   -0.396146   -0.031345   -0.037794    0.007014   
51224   -0.028048   -0.018882   -0.600346   -0.044087   -0.041079   -0.019087   
43482   -0.082098   -0.077837   -2.334726   -0.147539   -0.145945   -0.035644   
...           ...         ...         ...         ...         ...         ...   
16201   -0.052100   -0.016978   -0.254413    0.003165    0.016450   -0.053880   
50218   -0.031186   -0.031746   -1.172970   -0.074587   -0.074069   -0.018875   
17706    0.011297    0.010556   -0.338343   -0.024960   -0.025878    0.025341   
40535    0.047556    0.051649    1.209845    0.045982    0.018709    0.030525   
24636    0.017611    0.029274    0.266538    0.008867    0.004677    0.026393   

       fiberMag_g  fiberMag_r  fiberMag_i  fiberMag_z  ...      zerr  \
37223    0.042999    1.239828    0.057163    0.045839  ... -0.009194   
43793   -0.016666   -0.399860   -0.009298    0.005945  ... -0.009259   
48047    0.007081   -0.419491   -0.034272   -0.041500  ... -0.009236   
51224   -0.015296   -0.589041   -0.048165   -0.041646  ... -0.009262   
43482   -0.040069   -1.574268   -0.098393   -0.098120  ... -0.009263   
...           ...         ...         ...         ...  ...       ...   
16201   -0.025336   -0.633932   -0.018101    0.000204  ... -0.009131   
50218   -0.024586   -1.185353   -0.075366   -0.073134  ... -0.009255   
17706    0.018085   -0.118501   -0.010381   -0.012628  ... -0.009231   
40535    0.054897    1.574645    0.062764    0.031617  ... -0.009212   
24636    0.028403    0.264157    0.006939    0.001009  ... -0.009231   

           mmug      mmgr      mmri      mmiz      mfug      mfgr      mfri  \
37223  0.075962  0.106960  0.146593  0.065833  0.053682  0.075670  0.139644   
43793 -0.070209 -0.119083 -0.218671 -0.120537 -0.018585 -0.027199 -0.035959   
48047  0.004104 -0.007194 -0.057662 -0.042291  0.007335 -0.003999 -0.062081   
51224 -0.024424 -0.038287 -0.083992 -0.052094 -0.017894 -0.030824 -0.087215   
43482 -0.083233 -0.153296 -0.302889 -0.179517 -0.039402 -0.081571 -0.202954   
...         ...       ...       ...       ...       ...       ...       ...   
16201 -0.035953 -0.025186 -0.013892  0.011999 -0.041227 -0.042037 -0.060346   
50218 -0.032751 -0.069669 -0.152632 -0.090930 -0.022618 -0.055841 -0.154088   
17706  0.011373 -0.000416 -0.047449 -0.031096  0.022600  0.014937 -0.018232   
40535  0.051628  0.090733  0.126687  0.039569  0.044454  0.096391  0.167583   
24636  0.024398  0.037854  0.026656  0.008285  0.028517  0.035342  0.024546   

           mfiz    z_phot  
37223  0.059426  3.138619  
43793 -0.001935  0.150816  
48047 -0.043716  0.510792  
51224 -0.051816  0.510563  
43482 -0.113377  0.115536  
...         ...       ...  
16201 -0.010325  2.589062  
50218 -0.085676  1.820182  
17706 -0.013275  2.862507  
40535  0.054452  0.043660  
24636  0.004586  1.414909  

[41823 rows x 27 columns]

In [ ]:
co_classifier = keras.Sequential()
co_classifier.add(layers.Dense(26))
co_classifier.add(layers.Dense(8,  activation='relu'))
co_classifier.add(layers.Dense(64, activation='relu'))
co_classifier.add(layers.Dense(256,  activation='relu'))
co_classifier.add(layers.Dense(8,  activation='tanh'))
co_classifier.add(layers.Dense(64,  activation='elu'))
co_classifier.add(layers.Dense(2, activation='softmax'))



In [ ]:
learning_rate = 0.00001
co_classifier.compile(
    loss='binary_crossentropy', 
    optimizer=keras.optimizers.Adam(learning_rate=learning_rate), 
    metrics=['acc']
)

In [ ]:
history = co_classifier.fit(
    train_x, 
    train_y,
    validation_data= (val_x,val_y), 
    epochs=10,
    batch_size = 64 
)

Epoch 1/10
654/654 [==============================] - 4s 4ms/step - loss: 0.6815 - acc: 0.6361 - val_loss: 0.6632 - val_acc: 0.6925
Epoch 2/10
654/654 [==============================] - 2s 3ms/step - loss: 0.6321 - acc: 0.7560 - val_loss: 0.6013 - val_acc: 0.7874
Epoch 3/10
654/654 [==============================] - 2s 3ms/step - loss: 0.5673 - acc: 0.7978 - val_loss: 0.5437 - val_acc: 0.8012
Epoch 4/10
654/654 [==============================] - 2s 3ms/step - loss: 0.5226 - acc: 0.8064 - val_loss: 0.5113 - val_acc: 0.8072
Epoch 5/10
654/654 [==============================] - 2s 3ms/step - loss: 0.4978 - acc: 0.8117 - val_loss: 0.4915 - val_acc: 0.8113
Epoch 6/10
654/654 [==============================] - 2s 3ms/step - loss: 0.4808 - acc: 0.8155 - val_loss: 0.4766 - val_acc: 0.8139
Epoch 7/10
654/654 [==============================] - 2s 3ms/step - loss: 0.4669 - acc: 0.8168 - val_loss: 0.4641 - val_acc: 0.8154
Epoch 8/10
654/654 [==============================] - 2s 3ms/step - loss: 0.

In [ ]:
test_y_pred = co_classifier.predict(test_x)

162/162 [==============================] - 0s 1ms/step


In [ ]:
test_y_pred

array([[0.10740309, 0.89259684],
       [0.07716674, 0.9228333 ],
       [0.09421235, 0.9057875 ],
       ...,
       [0.9986003 , 0.00139966],
       [0.08611914, 0.9138808 ],
       [0.07284719, 0.9271528 ]], dtype=float32)

In [ ]:
test_y

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [ ]:
label_pred = []
label_expected = []
for i in range(test_y_pred.shape[0]):
    if test_y_pred[i][0]>test_y_pred[i][1]:
        label_pred.append("NO")
    else:
        label_pred.append("CO")
        
for i in range(test_y.shape[0]):
    if test_y[i][0]>test_y[i][1]:
        label_expected.append("NO")
    else:
        label_expected.append("CO")
        

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
true_co = 0
expected_co = 0
detected_co = 0

for i in range(len(test_y)):
    if label_pred[i]=='CO':
        detected_co+=1
    if label_expected[i]=='CO':
        expected_co+=1
    if label_expected[i]=='CO' and label_pred[i]=='CO':
        true_co+=1

print("%CO detected : ", (true_co*100)/expected_co)

%CO detected :  95.03273007316135


In [ ]:
true_no = 0
expected_no = 0
detected_no = 0

for i in range(len(test_y)):
    if label_pred[i]=='NO':
        detected_no+=1
    if label_expected[i]=='NO':
        expected_no+=1
    if label_expected[i]=='NO' and label_pred[i]=='NO':
        true_no+=1

print("%NO detected : ", (true_no*100)/expected_no)

%NO detected :  72.22438644331905
